// DO NOT EDIT.
// This file was generated automatically
// from gen.go. Please do not edit this file.

/*
package md2 is a 64-bit 2D math package based around the Vec type.

The names in geometry module stand for
(m)ath for (s)hort/(d)ouble floats in (2)D/(3)D.
"short" since there are no native 16 bit floats in Go.
*/
package md2
